// "use client"

// import { useState } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster";

// import { createContext } from "react";
// import { Project } from "@/interfaces/project";
import { ProjectProvider } from "./ProjectContext";
// export const ProjectContextData = createContext({} as { localProject: Project, setLocalProject: React.Dispatch<React.SetStateAction<Project>> });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>

      <ClerkProvider>
        <html suppressHydrationWarning lang="en">

          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ProjectProvider>

              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange>

                {children}
                <Toaster />
              </ThemeProvider>
            </ProjectProvider>
          </body>

        </html>

      </ClerkProvider >

    </>


  );
}
